overwrite: true
schema:
  - ${NEXT_PUBLIC_TAKESHAPE_API_URL}:
      headers:
        Authorization: Bearer ${NEXT_PUBLIC_TAKESHAPE_ANONYMOUS_API_KEY}
  - "https://deluxe-sample-project.myshopify.com/api/2022-04/graphql.json":
      headers:
        "X-Shopify-Storefront-Access-Token": "01dbab55cc6247e7558e76b7ce17b340"
documents: src/**/*.{graphql,js,ts,jsx,tsx}
# extensions:
#   codegen:
#     generates:
    #   ./src/types/storefront.ts:
    #     # documents: src/**/*.{graphql,js,ts,jsx,tsx}
    #     documents: src/**/queries.storefront.ts
    #     schema:
    #       - "https://deluxe-sample-project.myshopify.com/api/2022-04/graphql.json":
    #           headers:
    #             "X-Shopify-Storefront-Access-Token": "01dbab55cc6247e7558e76b7ce17b340"
    #     plugins:
    #       - typescript
    #       - typescript-operations
    #     config:
    #       omitOperationSuffix: true
    #       operationResultSuffix: Response

    #   ./src/types/takeshape.ts:
    #     # documents: src/**/*.{graphql,js,ts,jsx,tsx}
    #     documents: src/**/queries.ts
    #     schema:
    #       - ${NEXT_PUBLIC_TAKESHAPE_API_URL}:
    #           headers:
    #             Authorization: Bearer ${NEXT_PUBLIC_TAKESHAPE_ANONYMOUS_API_KEY}
    #     plugins:
    #       - typescript
    #       - typescript-operations
    #     config:
    #       omitOperationSuffix: true
    #       operationResultSuffix: Response

