export const PRODUCT_NAME = process.env.PLAYWRIGHT_PRODUCT_NAME;
export const PRODUCT_OUTOFSTOCK = process.env.PLAYWRIGHT_PRODUCT_NAME_OUTOFSTOCK;
export const PRODUCT_COLOR_OUTOFSTOCK = process.env.PLAYWRIGHT_PRODUCT_COLOR_OUTOFSTOCK;
export const PRODUCT_SIZE_OUTOFSTOCK = process.env.PLAYWRIGHT_PRODUCT_SIZE_OUTOFSTOCK;
export const HOMEPAGE_ENDPOINT = '/';
export const COLLECTION_NAME = process.env.PLAYWRIGHT_COLLECTION_NAME;
export const COLLECTIONS_ENDPOINT = '/collections/';
