#!/bin/sh

if sh -c ": >/dev/tty" >/dev/null 2>/dev/null; then
  exec < /dev/tty
  npm run --silent takeshape:post-merge-hook -- --tty
else
  npm run --silent takeshape:post-merge-hook -- --no-tty
fi

