#!/bin/sh

if [[ "$3" == "0" ]]; then
  exit;
fi

if [ "$1" == "$2" ]; then
  set +e

  # Test whether a remote for this branch exists
  output=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>&1) && exit_status=$? || exit_status=$?

  if [[ $exit_status -ne 0 ]]; then
    echo "Possible new branch creation detected"

    exec < /dev/tty

    npm run post-checkout
  fi
fi
