#!/bin/sh

if [[ "$3" == "0" ]]; then
  exit;
fi

if [ "$1" == "$2" ]; then
  # Test whether a remote for this branch exists
  upstream=`git rev-parse --abbrev-ref --symbolic-full-name @{u}`

  if [[ $upstream -eq 1 ]]; then
    echo "Possible new branch creation detected"

    exec < /dev/tty

    ./scripts/post-checkout.mjs
  fi
fi
