name: Lighthouse (Production)

on:
  deployment_status:

jobs:
  lighthouse-run:
    name: Audit
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Audit URLs using Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v9
        env:
          LIGHTHOUSE_CONFIG: 'production'
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
            ${{ github.event.deployment_status.target_url }}/product/__lighthouse
            ${{ github.event.deployment_status.target_url }}/collection/__lighthouse
          configPath: ./.lighthouse/lighthouserc.js
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 5

      - name: Format Lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v6
        with:
          script: |
            const lighthouseCommentMaker = require('./.lighthouse/lighthouseCommentMaker.js');

            const lighthouseOutputs = {
              manifest: ${{ steps.lighthouse_audit.outputs.manifest }},
              links: ${{ steps.lighthouse_audit.outputs.links }}
            };

            const comment = lighthouseCommentMaker({ lighthouseOutputs });
            core.setOutput("comment", comment);

      - name: Add Lighthouse to README.md
        if: always()
        run: |
          begin="<!-- LIGHTHOUSE:START -->"
          end="<!-- LIGHTHOUSE:END -->"
          data="${{ steps.format_lighthouse_score.outputs.comment }}"
          file="README.md"
          awk -i inplace \
            -v begin="$begin" \
            -v end="$end" \
            -v data="$data" '$0~end{f=0} !f{print} $0~begin{print data;f=1}' \
            "$file"

      - name: Commit to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Lighthouse Score [skip ci]
          branch: main
          commit_user_name: lighthouse-action
          commit_user_email: actions@github.com
          commit_author: lighthouse-action <actions@github.com>
